# cursor size
cursor_size=24
env=XCURSOR_SIZE,24

# fcitx5 im
env=GTK_IM_MODULE,fcitx
env=QT_IM_MODULE,fcitx
env=SDL_IM_MODULE,fcitx
env=XMODIFIERS,@im=fcitx
env=GLFW_IM_MODULE,ibus

# scale factor about qt (herr is 1.4)
env=QT_QPA_PLATFORMTHEME,qt5ct
env=QT_AUTO_SCREEN_SCALE_FACTOR,1
env=QT_QPA_PLATFORM,Wayland;xcb
env=QT_WAYLAND_FORCE_DPI,140


###############################
#         bind                #
###############################

# Key Bindings
# key name refer to `xev` or `wev` command output,
# mod keys name: super,ctrl,alt,shift,none

# reload config
bind=SUPER+SHIFT,r,reload_config

bind=,Print,exec,grim -g "$(slurp -d)" - | swappy -f -


# exit
bind=SUPER+SHIFT,q,quit
bind=SUPER,q,killclient,

# menu and terminal
bind=SUPER,p,spawn,pkill wofi || wofi --show drun
bind=SUPER,Return,spawn,kitty
bind=Alt,Return,spawn,foot


###############################
#         exec                #
###############################

exec-once=mkdir -p ~/screenshots
exec-once=libinput-gestures > /tmp/libinput-gestures-npc.log 2>&1 &
exec-once=fcitx5 -d --replace
exec-once=swaybg -m fill -i ~/.config/wallpapers/arch.png
exec-once=swaync-client -swb
exec-once=brightnessctl s 50%
exec-once=pamixer --set-volume 50
exec-once=foot --server
exec-once=nm-applet --indicator
exec-once=blueman-applet
exec-once=libinput-gestures-setup restart
exec-once=clash-verge

# NOTE: 自动启动之后不能 kill 之后重新设置
# 改为手动设置
#             日出      日落    最小  最大
# exec-once=wlsunset -S 06:30 -s 18:00 -t 2000 -T 4200

