add_newline = true
command_timeout = 2000
scan_timeout = 2

format = "$time $all"

[time]
disabled = false
format = "🕒 [$time]($style)"
time_format = "%H:%M:%S"
style = "bold dimmed yellow"

[c]
symbol = "[ ](black)"

[character]
error_symbol = "[](bold red)"
format = "$symbol [|](bold bright-black) "
success_symbol = "[](bold green)"
vicmd_symbol = "[](bold yellow)"

[directory]
format = "[ ](bold green) [$path]($style) "
truncation_length = 2

[git_branch]
style = "bold purple"

[git_commit]
commit_hash_length = 7

[git_status]
ahead = "⇡ "
behind = "⇣ "
conflicted = " "
deleted = "✘ "
diverged = "⇆ "
modified = "!"
renamed = "»"
staged = "+"
stashed = "≡"
style = "red"
untracked = "?"

[golang]
symbol = "[󰟓 ](blue)"

[hostname]
disabled = false
format = "@[$hostname](bold blue) "
ssh_only = true

[line_break]
disabled = false

[lua]
symbol = "[ ](blue) "

[nix_shell]
symbol = "[󱄅 ](blue) "

[nodejs]
symbol = "[󰎙 ](yellow)"

[package]
symbol = "📦 "

[python]
symbol = "[ ](blue) "

[rust]
symbol = "[ ](red) "

# 不显示 docker/kubernetes 等模块
[docker_context]
disabled = true

[kubernetes]
disabled = true

[username]
format = "[$user]($style) in "

