{...}: {
  # vars
  username = "npc";
  userfullname = "npc z";
  useremail = "1763998996@qq.com";

  # generated by `mkpasswd -m scrypt`
  initialHashedPassword = "$7$CU..../....tZezIQoagIa3b7.jb5hHF1$c.VOTYgMs2imdHIyqNLXBDSqJ9i6OSgBGWxMVdQgDAC";
}
