{...}: rec {
  # vars
  username = "npc";
  userfullname = "npc z";
  useremail = "1763998996@qq.com";

  # NOTE: 本仓库在本地的位置 change these vars to the real value
  thisRepoName = "nixos";
  thisRepoPathAtNixos = "/home/${username}/.config/${thisRepoName}";
  thisRepoPathAtDarwin = "/Users/${username}/.config/${thisRepoName}";

  # generated by `mkpasswd -m scrypt`
  initialHashedPassword = "$7$CU..../....tZezIQoagIa3b7.jb5hHF1$c.VOTYgMs2imdHIyqNLXBDSqJ9i6OSgBGWxMVdQgDAC";
}
