{...}: rec {
  # vars
  username = "npc";
  userFullName = "npc z";
  useremail = "1763998996@qq.com";
  gitUserName = "npc-z";

  # NOTE: 本仓库在本地的位置 change these vars to the real value
  thisRepoName = "nixos";
  thisRepoPathAtNixos = "/home/${username}/.config/${thisRepoName}";
  thisRepoPathAtDarwin = "/Users/${username}/.config/${thisRepoName}";

  # generated by `mkpasswd -m scrypt --rounds=11`
  # https://man.archlinux.org/man/crypt.5.en
  # initialHashedPassword = "$7$GU..../....QA0BFxUjVU75WVhyXDGrK1$WoMR2fNR7rm4CjLGl5/DY4OoCwJuHc7uuCVBe8Tk.z6";
  # 生成命令：mkpasswd -m yescrypt, 使用体感比 scrypt 生成的哈希更快
  initialHashedPassword = "$y$j9T$r5ZGx6UGtCQJunL4E3.g./$Y0m6Bc83WdQhmlhsBtwQ1OOmMFIqLdOCCJMMsjl8Wg1";
}
