[General]
%23%20activate_item_on_single_click=1
%23%20buttonbox_layout=0
%23%20cursor_flash_time=1000
%23%20custom_palette=false
%23%20dialog_buttons_have_icons=1
%23%20double_click_interval=400
%23%20fixed="Maple Mono NF CN,9,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,Regular"
%23%20force_raster_widgets=1
%23%20general="Maple Mono NF CN,9,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,Regular"
%23%20geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x3\xad\0\0\x3\xea\0\0\0\0\0\0\0\0\0\0\x3\xad\0\0\x3\xea\0\0\0\0\0\0\0\0\a\x80\0\0\0\0\0\0\0\0\0\0\x3\xad\0\0\x3\xea)
%23%20gui_effects=@Invalid()
%23%20icon_theme=Papirus
%23%20ignored_applications=@Invalid()
%23%20keyboard_scheme=2
%23%20menus_have_icons=true
%23%20show_shortcuts_in_context_menus=true
%23%20standard_dialogs=default
%23%20style=Fusion
%23%20stylesheets=@Invalid()
%23%20toolbutton_style=4
%23%20underline_shortcut=1
%23%20wheel_scroll_lines=3

[Appearance]
custom_palette=false
icon_theme=Adwaita
standard_dialogs=default
style=Fusion

[Fonts]
fixed="Maple Mono NF CN,12,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,Regular,0,0"
general="Maple Mono NF CN,12,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,Regular,0,0"

[Interface]
activate_item_on_single_click=1
buttonbox_layout=0
cursor_flash_time=1000
dialog_buttons_have_icons=1
double_click_interval=400
gui_effects=@Invalid()
keyboard_scheme=2
menus_have_icons=true
show_shortcuts_in_context_menus=true
stylesheets=@Invalid()
toolbutton_style=4
underline_shortcut=1
wheel_scroll_lines=3

[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x3\xad\0\0\x3\xea\0\0\0\0\0\0\0\0\0\0\x3\xad\0\0\x3\xea\0\0\0\0\0\0\0\0\a\x80\0\0\0\0\0\0\0\0\0\0\x3\xad\0\0\x3\xea)

[Troubleshooting]
force_raster_widgets=1
ignored_applications=@Invalid()
