monitor = , preferred, auto, 1

# source = ~/.config/hypr/hosts/ser7.conf
# source = ~/.config/hypr/hosts/r9000p.conf
# source = ~/.config/hypr/hosts/thinkpad.conf

# Some default env vars.
env = XCURSOR_SIZE, 24
# XDG Specifications
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

env = QT_QPA_PLATFORMTHEME, qt6ct

dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
}

master {
    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    mfact = 0.5
    new_status = true
    new_on_top = true
}

gestures {
    # https://wiki.hypr.land/Configuring/Gestures/
    workspace_swipe_distance = 110
}
gesture = 4, horizontal, workspace

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

misc {
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
}

cursor {
    hide_on_key_press = true
}
