$mainMod = SUPER

# run listener on startup
exec-once = clipse -listen

# ensure you have defined a floating window class
windowrule = float on, match:class (floatingClipse)

# bind the open clipboard operation to a nice key.
bind = $mainMod, V, exec, alacritty --class floatingClipse -e zsh -c 'clipse $PPID'

