windowrule = float on, match:class ^(Bytedance-feishu)$
windowrule = float on, match:title ^(.*会话记录.*)$
windowrule = float on, match:title ^(.*飞书会议.*)$
# 退出飞书视频会议时使用下面这条规则，否则退出按钮无法保持（移动鼠标后一闪而过）
# windowrule = float on, stay_focused on, min_size 1 1, match:title ^(.*飞书会议.*)$
windowrule = float on, match:class ^(Bytedance)$

